version: '3.7'


networks:
  corey-regan-net:
    external: true


services:
  portfolio:
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 0s
    environment:
      APP_ENV: prod
    image: ghcr.io/invincibear/corey-regan.ca-portfolio:latest
    networks:
      - corey-regan-net
    ports:
      - "8071:3000"  # external:internal

  blog:
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 0s
    environment:
      APP_ENV: prod
    image: ghcr.io/invincibear/corey-regan.ca-blog:latest
    networks:
      - corey-regan-net
    ports:
      - "8070:3000"  # external:internal
