name: Deploy portfolio


on:
  push:
    branches:
      - main


jobs:
  build_and_push_image:
    name: Build and push image to GHCR.io
    runs-on:         ${{ vars.RUNNER }}
    timeout-minutes: 10

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id:   meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ vars.REGISTRY }}/${{ github.repository }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context:   .
          file:      Dockerfile
          labels:    ${{ steps.meta.outputs.labels }}
          platforms: "linux/amd64"
          push:      true
          tags:      |
            ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}
            ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}:latest

  deploy_image:
    name:            Deploy image to VPS
    needs:           build_and_push_image
    runs-on:         ${{ vars.RUNNER }}
    timeout-minutes: 10

    steps:
      - name: Log into registry
        run:  echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ vars.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Pull Docker image
        run:  docker pull ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to VPS
        run:  |
          docker service update --image ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ github.sha }} ${{ vars.DOCKER_SERVICE_NAME }}_portfolio
          docker stack deploy --detach=true -c ${{ vars.DOCKER_COMPOSE_PATH }}/docker-compose.yml ${{ vars.DOCKER_SERVICE_NAME }}
